# Generated by Django 5.1.3 on 2024-11-17 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ponderation',
            options={'verbose_name': 'Rating', 'verbose_name_plural': 'Ratings'},
        ),
    ]
