# Generated by Django 5.1.3 on 2024-11-17 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0002_alter_ponderation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponderation',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer_service.reservation'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='number_of_cards',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reservation',
            name='subscription_type',
            field=models.CharField(choices=[('MONTHLY', 'Monthly'), ('ANNUAL', 'Annual'), ('CARDS', 'Cards Package')], default='MONTHLY', max_length=20),
        ),
    ]
