# Generated by Django 5.1.3 on 2024-11-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0003_ponderation_reservation_reservation_number_of_cards_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
